import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jobs Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devchallenges.png" />
      </Head>

      <main>App</main>
    </div>
  );
}
